spring.application.name: heroes-account-cdc
       
spring.kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#temporary list of accounts for the coro-pool
account:
  accounts[0]: foo
  accounts[1]: goo
  accounts[2]: bar
  accounts[3]: baz
  