spring.application.name: heroes-account-cdc-app
       
spring.kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#temporary list of accounts for the coro-pool
account:
  accounts[0]: foo
  accounts[1]: goo
  accounts[2]: bar
  accounts[3]: baz
  accounts[4]: aaa
  accounts[5]: bbb
  accounts[6]: ccc
  accounts[7]: ddd
  accounts[8]: eee
  accounts[9]: fff
  accounts[10]: ggg
  accounts[11]: hhh
  accounts[12]: iii
  accounts[13]: jjj
  accounts[14]: kkk
  accounts[15]: lll
  accounts[16]: mmm
  accounts[17]: nnn
  accounts[18]: ooo
  accounts[19]: ppp
  accounts[20]: qqq
  accounts[21]: rrr
  accounts[22]: sss
  accounts[23]: ttt
  accounts[24]: uuu
  accounts[25]: vvv
  accounts[26]: www
  accounts[27]: xxx
  accounts[28]: yyy
  accounts[29]: zzz
  