spring.application.name: heroes-transfer-tupler
       
spring.kafka:
  bootstrap-servers: localhost:9092

  # streams configurations
  streams.properties:
    default:
      key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        