apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transfer-validation-response
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000