---
version: '2'
services:
  bigbrother-transfer-is-pair:
   image: leonardobonacci/heroes-bigbrother-transfer-is-pair
   build: bigbrother-transfer-is-pair
   depends_on:
     - broker
   environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE:-docker}

  bigbrother-transfer-is-processed:
   image: leonardobonacci/heroes-bigbrother-transfer-is-processed
   build: bigbrother-transfer-is-processed
   depends_on:
     - broker
   environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE:-docker}
