spring.application.name: heroes-account-cache-app
       
spring.kafka:
  bootstrap-servers: localhost:9092

  # streams configurations
  streams.properties:
    default:
      key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    max.poll.records: 1 # consumer
                 
  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.value.default.type: guru.bonacci.heroes.domain.Account
    auto-offset-reset: earliest # consumer