spring.application.name: do-not-forget-to-change-me

#temporary list of accounts for the heroes-pool
account:
  accounts[0]: a
  accounts[1]: aa
  accounts[2]: ab
  accounts[3]: ac
  accounts[4]: b
  accounts[5]: c

spring.kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaJsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaJsonDeserializer
      properties:
        json.fail.unknown.properties: false
        json.value.type: guru.bonacci.heroes.domain.Account