spring.application.name: heroes-account-store-app

server:
  port: 8080
  
spring.kafka:
  bootstrap-servers: localhost:9092

  # streams configurations
  streams.properties:
    processing.guarantee: exactly_once
    default:
      key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    cache.max.bytes.buffering: 0
    application.server: ${spring.cloud.client.ip-address}:${server.port}
    state.dir: /tmp/${spring.cloud.client.ip-address}:${server.port} 