spring.application.name: heroes-account-initializer
       
spring.kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#temporary list of accounts for the coro-pool
account:
  accounts[0]: a
  accounts[1]: aa
  accounts[2]: ab
  accounts[3]: ac
  accounts[4]: b
  accounts[5]: c