spring.application.name: heroes-account-transfers-initializer

spring.profiles.active: docker
    
spring:
  kafka:
    bootstrap-servers: localhost:9092

    streams.properties:
      default:
        key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        auto-offset-reset: earliest           

---

spring:
  profiles: docker

  kafka:
    bootstrap-servers: broker:29092

    streams.properties:
      default:
        key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        auto-offset-reset: earliest           
      