apiVersion: v1
kind: Service
metadata:
  name: account-store-service
spec:
  selector:
    app: account-store-app
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-store-app
spec:
  selector:
    matchLabels:
      app: account-store-app
  replicas: 5
  template:
    metadata:
      labels:
        app: account-store-app
    spec:
      containers:
        - name: account-store-app
          image: leonardobonacci/heroes-account-store
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
